Import pandas

In [ ]:
import pandas as pd

Create a DatetimeIndex with 3 different timestamps and assign it to a variable called `dates`

In [8]:
dates = ['2025-01-01', '2025-02-01', '2025-03-01']
dates = pd.to_datetime(dates)
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01'], dtype='datetime64[ns]', freq=None)

Find the time between each one of these dates

In [10]:
diff_first_second = dates[0] - dates[1]
diff_first_third = dates[0] - dates[2]
diff_second_third = dates[1] - dates[2]
print(diff_first_second, diff_first_third, diff_second_third)

-31 days +00:00:00 -59 days +00:00:00 -28 days +00:00:00

Create a DataFrame with the `dates` as the index and add 3 new columns that hold the day name, month name, and the year.

In [12]:
dates_df = pd.DataFrame(index= dates, columns= ['day name', 'month name','year'])
dates_df

           day name month name year
2025-01-01      NaN        NaN  NaN
2025-02-01      NaN        NaN  NaN
2025-03-01      NaN        NaN  NaN

Fill in the gaps of our DataFrame with every missing date (between our 3 dates), and make sure there are no NaNs

In [17]:
dates_df['day name'] = dates_df.index.day_name()
dates_df['month name'] = dates_df.index.month_name()
dates_df['year'] = dates_df.index.year
dates_df

             day name month name  year
2025-01-01  Wednesday    January  2025
2025-02-01   Saturday   February  2025
2025-03-01   Saturday      March  2025

Convert our DatetimeIndex to a PeriodIndex which represents a whole day per date.

In [20]:
dates_df_period = dates_df.to_period()
dates_df_period

          day name month name  year
2025-01  Wednesday    January  2025
2025-02   Saturday   February  2025
2025-03   Saturday      March  2025