Import Pandas

In [1]:
import pandas as pd

Read the `pokemon.csv` file and set the index to `['Type 1', 'Name']`

In [2]:
poke = pd.read_csv('Pokemon.csv', index_col=['Type 1', 'Name'])
poke

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45      49       49
        Ivysaur                  2  Poison    405  60      62       63
        Venusaur                 3  Poison    525  80      82       83
        VenusaurMega Venusaur    3  Poison    625  80     100      123
Fire    Charmander               4     NaN    309  39      52       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50     100      150
        DiancieMega Diancie    719   Fairy    700  50     160      110
Psychic HoopaHoopa Confined    720   Ghost    600  80     110       60
        HoopaHoopa Unbound     720    Dark    680  80     160       60
Fire    Volcanion              721   Water    600  80     110      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]

Sort the pokemons by `Type 1`

In [11]:
poke.sort_values('Type 1', inplace=True)
poke

                    #    Type 2  Total   HP  Attack  Defense  Sp. Atk  \
Type 1 Name
Bug    Sewaddle   540     Grass    310   45      53       70       40
       Spinarak   167    Poison    250   40      60       40       40
       Ledian     166    Flying    390   55      35       50       55
       Nincada    290    Ground    266   31      45       90       30
       Ledyba     165    Flying    265   40      20       30       40
...               ...       ...    ...  ...     ...      ...      ...
Water  Gastrodon  423    Ground    475  111      83       68       92
       Shellos    422       NaN    325   76      48       48       57
       Floatzel   419       NaN    495   85     105       55       85
       Clamperl   366       NaN    345   35      64       85       74
       Chinchou   170  Electric    330   75      38       38       56

                  Sp. Def  Speed  Generation  Legendary
Type 1 Name
Bug    Sewaddle        60     42           5      False
       Spinarak        40     30           2      False
       Ledian         110     85           2      False
       Nincada         30     40           3      False
       Ledyba          80     55           2      False
...                   ...    ...         ...        ...
Water  Gastrodon       82     39           4      False
       Shellos         62     34           4      False
       Floatzel        50    115           4      False
       Clamperl        55     32           3      False
       Chinchou        56     67           2      False

[800 rows x 11 columns]

Select all the `Fire` pokemons that start with the letter `C`

In [22]:
fire_poke = poke.loc['Fire']
fire_poke[fire_poke.index.str.startswith('C')]

,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Charizard,6,Flying,534,78,84,78,109,85,100,1,False
CharizardMega Charizard X,6,Dragon,634,78,130,111,130,85,100,1,False
CharizardMega Charizard Y,6,Flying,634,78,104,78,159,115,100,1,False
Charmeleon,5,NaN,405,58,64,58,80,65,80,1,False
Charmander,4,NaN,309,39,52,43,60,50,65,1,False
Cyndaquil,155,NaN,309,39,52,43,60,50,65,2,False
Camerupt,323,Ground,460,70,100,70,105,75,40,3,False
Chimchar,390,NaN,309,44,58,44,58,44,61,4,False
Combusken,256,Fighting,405,60,85,60,85,60,55,3,False
CameruptMega Camerupt,323,Ground,560,70,120,100,145,105,20,3,False

Using `agg()` get the `max`, `min` and the `mean` of all the pokemons for the columns `['Attack', 'Defense']` and round them to 1 decimal place.

In [25]:
poke.agg({'Attack': ['max', 'min', 'mean'], 'Defense': ['max', 'min', 'mean']}).round(1)

      Attack  Defense
max    190.0    230.0
min      5.0      5.0
mean    79.0     73.8

Create a function that checks the Attack of a pokemon. If the `Attack` is over 100, it should now display `'STRONG'`, if it is less than that, it should display `'WEAK'`. Update the DataFrame to display this new Attack column`

In [26]:
def strenght(attack: int) -> str:
    if attack > 100:
        return 'STRONG'
    else:
        return 'WEAK'

In [27]:
poke['Attack'] = poke['Attack'].apply(strenght)
poke

                    #    Type 2  Total   HP  Attack  Defense  Sp. Atk  \
Type 1 Name
Bug    Sewaddle   540     Grass    310   45    WEAK       70       40
       Spinarak   167    Poison    250   40    WEAK       40       40
       Ledian     166    Flying    390   55    WEAK       50       55
       Nincada    290    Ground    266   31    WEAK       90       30
       Ledyba     165    Flying    265   40    WEAK       30       40
...               ...       ...    ...  ...     ...      ...      ...
Water  Gastrodon  423    Ground    475  111    WEAK       68       92
       Shellos    422       NaN    325   76    WEAK       48       57
       Floatzel   419       NaN    495   85  STRONG       55       85
       Clamperl   366       NaN    345   35    WEAK       85       74
       Chinchou   170  Electric    330   75    WEAK       38       56

                  Sp. Def  Speed  Generation  Legendary
Type 1 Name
Bug    Sewaddle        60     42           5      False
       Spinarak        40     30           2      False
       Ledian         110     85           2      False
       Nincada         30     40           3      False
       Ledyba          80     55           2      False
...                   ...    ...         ...        ...
Water  Gastrodon       82     39           4      False
       Shellos         62     34           4      False
       Floatzel        50    115           4      False
       Clamperl        55     32           3      False
       Chinchou        56     67           2      False

[800 rows x 11 columns]

Create a new column called `Reversed` which holds each pokemon name reversed

In [28]:
poke['Reversed'] = poke.index.get_level_values('Name').str[::-1]
poke

                    #    Type 2  Total   HP  Attack  Defense  Sp. Atk  \
Type 1 Name
Bug    Sewaddle   540     Grass    310   45    WEAK       70       40
       Spinarak   167    Poison    250   40    WEAK       40       40
       Ledian     166    Flying    390   55    WEAK       50       55
       Nincada    290    Ground    266   31    WEAK       90       30
       Ledyba     165    Flying    265   40    WEAK       30       40
...               ...       ...    ...  ...     ...      ...      ...
Water  Gastrodon  423    Ground    475  111    WEAK       68       92
       Shellos    422       NaN    325   76    WEAK       48       57
       Floatzel   419       NaN    495   85  STRONG       55       85
       Clamperl   366       NaN    345   35    WEAK       85       74
       Chinchou   170  Electric    330   75    WEAK       38       56

                  Sp. Def  Speed  Generation  Legendary   Reversed
Type 1 Name
Bug    Sewaddle        60     42           5      False   elddaweS
       Spinarak        40     30           2      False   karanipS
       Ledian         110     85           2      False     naideL
       Nincada         30     40           3      False    adacniN
       Ledyba          80     55           2      False     abydeL
...                   ...    ...         ...        ...        ...
Water  Gastrodon       82     39           4      False  nodortsaG
       Shellos         62     34           4      False    sollehS
       Floatzel        50    115           4      False   leztaolF
       Clamperl        55     32           3      False   lrepmalC
       Chinchou        56     67           2      False   uohcnihC

[800 rows x 12 columns]

Reset the index so that only `Name` shows as the index

In [29]:
poke.reset_index('Type 1')

,Type 1,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Reversed
Name,,,,,,,,,,,,,
Sewaddle,Bug,540,Grass,310,45,WEAK,70,40,60,42,5,False,elddaweS
Spinarak,Bug,167,Poison,250,40,WEAK,40,40,40,30,2,False,karanipS
Ledian,Bug,166,Flying,390,55,WEAK,50,55,110,85,2,False,naideL
Nincada,Bug,290,Ground,266,31,WEAK,90,30,30,40,3,False,adacniN
Ledyba,Bug,165,Flying,265,40,WEAK,30,40,80,55,2,False,abydeL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gastrodon,Water,423,Ground,475,111,WEAK,68,92,82,39,4,False,nodortsaG
Shellos,Water,422,NaN,325,76,WEAK,48,57,62,34,4,False,sollehS
Floatzel,Water,419,NaN,495,85,STRONG,55,85,50,115,4,False,leztaolF
Clamperl,Water,366,NaN,345,35,WEAK,85,74,55,32,3,False,lrepmalC
Chinchou,Water,170,Electric,330,75,WEAK,38,56,56,67,2,False,uohcnihC