Import pandas

In [2]:
import pandas as pd

Read the `titanic3.xls` file and set 'name' as the index

In [4]:
titanic = pd.read_excel('titanic3.xls', index_col='name')
titanic.head()

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

Drop the following columns: `['home.dest', 'embarked', 'sibsp', 'parch']`

In [5]:
titanic.drop(columns=['home.dest', 'embarked', 'sibsp', 'parch'], inplace=True)
titanic.head()

,pclass,survived,sex,age,ticket,fare,cabin,boat,body
name,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,24160,211.3375,B5,2,NaN
"Allison, Master. Hudson Trevor",1,1,male,0.9167,113781,151.5500,C22 C26,11,NaN
"Allison, Miss. Helen Loraine",1,0,female,2.0000,113781,151.5500,C22 C26,NaN,NaN
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,113781,151.5500,C22 C26,NaN,135.0
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,113781,151.5500,C22 C26,NaN,NaN

Filter out all the passengers which did not survive.

In [8]:
titanic = titanic[titanic['survived'] ==1]
titanic

,pclass,survived,sex,age,ticket,fare,cabin,boat,body
name,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,24160,211.3375,B5,2,NaN
"Allison, Master. Hudson Trevor",1,1,male,0.9167,113781,151.5500,C22 C26,11,NaN
"Anderson, Mr. Harry",1,1,male,48.0000,19952,26.5500,E12,3,NaN
"Andrews, Miss. Kornelia Theodosia",1,1,female,63.0000,13502,77.9583,D7,10,NaN
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,1,female,53.0000,11769,51.4792,C101,D,NaN
...,...,...,...,...,...,...,...,...,...
"Turkula, Mrs. (Hedwig)",3,1,female,63.0000,4134,9.5875,NaN,15,NaN
"Vartanian, Mr. David",3,1,male,22.0000,2658,7.2250,NaN,13 15,NaN
"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",3,1,female,38.0000,2688,7.2292,NaN,C,NaN
"Wilkes, Mrs. James (Ellen Needs)",3,1,female,47.0000,363272,7.0000,NaN,NaN,NaN
"Yasbeck, Mrs. Antoni (Selini Alexander)",3,1,female,15.0000,2659,14.4542,NaN,NaN,NaN

Considering that the **body** column is only used for passengers who did not survive, drop that column, and then do the same thing for the **survived** column.

In [19]:
titanic.drop(columns= ['survived','body'],inplace=True)

What is the max **fare** in **3rd class**?

In [9]:
titanic[titanic['pclass']==3]['fare'].max()

np.float64(56.4958)

Rename the index name of 'name' to 'Passenger'

In [21]:
titanic.index.name= 'Passenger'
titanic.head()

,pclass,sex,age,ticket,fare,cabin,boat
Passenger,,,,,,,
"Allen, Miss. Elisabeth Walton",1,female,29.0000,24160,211.3375,B5,2
"Allison, Master. Hudson Trevor",1,male,0.9167,113781,151.5500,C22 C26,11
"Anderson, Mr. Harry",1,male,48.0000,19952,26.5500,E12,3
"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,13502,77.9583,D7,10
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,11769,51.4792,C101,D

**BONUS**

Create a new column that's called "Free Coffee", insert 1 if a passenger is either in 1st or 2nd class, otherwise insert 0

In [24]:
titanic['Free Coffee'] = 0
titanic.loc[titanic['pclass'].isin([1,2]), 'Free Coffee'] =1
titanic.head()

,pclass,sex,age,ticket,fare,cabin,boat,Free Coffee
Passenger,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,female,29.0000,24160,211.3375,B5,2,1
"Allison, Master. Hudson Trevor",1,male,0.9167,113781,151.5500,C22 C26,11,1
"Anderson, Mr. Harry",1,male,48.0000,19952,26.5500,E12,3,1
"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,13502,77.9583,D7,10,1
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,11769,51.4792,C101,D,1

Use value_counts() to verify that 3rd class doesn't get any free coffee

In [1]:
#titanic.loc[:, ['pclass','Free Coffee']].value_counts() 
titanic[['pclass', 'Free Coffee']].value_counts()

NameError: name 'titanic' is not defined