Import pandas

In [2]:
import pandas as pd

Read the `titanic3.xls` file and set 'name' as the index

In [4]:
tit = pd.read_excel('titanic3.xls', index_col='name')
tit

,pclass,survived,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
name,,,,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
"Allison, Master. Hudson Trevor",1,1,male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Miss. Helen Loraine",1,0,female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
"Zabour, Miss. Thamine",3,0,female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
"Zakarian, Mr. Ortin",3,0,male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

Drop the following columns: `['home.dest', 'embarked', 'sibsp', 'parch']`

In [ ]:
tit.drop(['home.dest', 'embarked', 'sibsp', 'parch'], axis=1, inplace=True)

,pclass,survived,sex,age,ticket,fare,cabin,boat,body
name,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,24160,211.3375,B5,2,NaN
"Allison, Master. Hudson Trevor",1,1,male,0.9167,113781,151.5500,C22 C26,11,NaN
"Allison, Miss. Helen Loraine",1,0,female,2.0000,113781,151.5500,C22 C26,NaN,NaN
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,113781,151.5500,C22 C26,NaN,135.0
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,113781,151.5500,C22 C26,NaN,NaN
...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,2665,14.4542,NaN,NaN,328.0
"Zabour, Miss. Thamine",3,0,female,NaN,2665,14.4542,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,2656,7.2250,NaN,NaN,304.0
"Zakarian, Mr. Ortin",3,0,male,27.0000,2670,7.2250,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,315082,7.8750,NaN,NaN,NaN

Filter out all the passengers which did not survive.

In [17]:
passengers_not_survived =tit[tit['survived'] == False]
passengers_not_survived

,pclass,survived,sex,age,ticket,fare,cabin,boat,body
name,,,,,,,,,
"Allison, Miss. Helen Loraine",1,0,female,2.0,113781,151.5500,C22 C26,NaN,NaN
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0,113781,151.5500,C22 C26,NaN,135.0
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0,113781,151.5500,C22 C26,NaN,NaN
"Andrews, Mr. Thomas Jr",1,0,male,39.0,112050,0.0000,A36,NaN,NaN
"Artagaveytia, Mr. Ramon",1,0,male,71.0,PC 17609,49.5042,NaN,NaN,22.0
...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5,2665,14.4542,NaN,NaN,328.0
"Zabour, Miss. Thamine",3,0,female,NaN,2665,14.4542,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5,2656,7.2250,NaN,NaN,304.0
"Zakarian, Mr. Ortin",3,0,male,27.0,2670,7.2250,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0,315082,7.8750,NaN,NaN,NaN

Considering that the **body** column is only used for passengers who did not survive, drop that column, and then do the same thing for the **survived** column.

In [ ]:
passengers_not_survived.drop(columns=['body'], inplace=True)
passengers_not_survived.drop(columns=['survived'], inplace=True)

What is the max **fare** in **3rd class**?

In [24]:
tit_3_class = tit[tit['pclass'] == 3]
tit_3_class_max_fare = tit_3_class['fare'].max()
tit_3_class_max_fare

np.float64(69.55)

Rename the index name of 'name' to 'Passenger'

In [25]:
tit.index.name = 'Passenger'
tit

,pclass,survived,sex,age,ticket,fare,cabin,boat,body
Passenger,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,24160,211.3375,B5,2,NaN
"Allison, Master. Hudson Trevor",1,1,male,0.9167,113781,151.5500,C22 C26,11,NaN
"Allison, Miss. Helen Loraine",1,0,female,2.0000,113781,151.5500,C22 C26,NaN,NaN
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,113781,151.5500,C22 C26,NaN,135.0
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,113781,151.5500,C22 C26,NaN,NaN
...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,2665,14.4542,NaN,NaN,328.0
"Zabour, Miss. Thamine",3,0,female,NaN,2665,14.4542,NaN,NaN,NaN
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,2656,7.2250,NaN,NaN,304.0
"Zakarian, Mr. Ortin",3,0,male,27.0000,2670,7.2250,NaN,NaN,NaN
"Zimmerman, Mr. Leo",3,0,male,29.0000,315082,7.8750,NaN,NaN,NaN

**BONUS**

Create a new column that's called "Free Coffee", insert 1 if a passenger is either in 1st or 2nd class, otherwise insert 0

In [8]:
tit['Free Coffe'] = 1
tit.loc[tit['pclass'] == 3, ['Free Coffe']] = 0
tit

,pclass,survived,sex,age,ticket,fare,cabin,boat,body,Free Coffe
name,,,,,,,,,,
"Allen, Miss. Elisabeth Walton",1,1,female,29.0000,24160,211.3375,B5,2,NaN,1
"Allison, Master. Hudson Trevor",1,1,male,0.9167,113781,151.5500,C22 C26,11,NaN,1
"Allison, Miss. Helen Loraine",1,0,female,2.0000,113781,151.5500,C22 C26,NaN,NaN,1
"Allison, Mr. Hudson Joshua Creighton",1,0,male,30.0000,113781,151.5500,C22 C26,NaN,135.0,1
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,0,female,25.0000,113781,151.5500,C22 C26,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
"Zabour, Miss. Hileni",3,0,female,14.5000,2665,14.4542,NaN,NaN,328.0,0
"Zabour, Miss. Thamine",3,0,female,NaN,2665,14.4542,NaN,NaN,NaN,0
"Zakarian, Mr. Mapriededer",3,0,male,26.5000,2656,7.2250,NaN,NaN,304.0,0
"Zakarian, Mr. Ortin",3,0,male,27.0000,2670,7.2250,NaN,NaN,NaN,0
"Zimmerman, Mr. Leo",3,0,male,29.0000,315082,7.8750,NaN,NaN,NaN,0

Use value_counts() to verify that 3rd class doesn't get any free coffee

In [16]:
tit_3_class = tit[tit['pclass'] == 3] 
tit_3_class['Free Coffe'].value_counts()

Free Coffe
0    709
Name: count, dtype: int64